version: "3"
services:
  ghost:
    image: ghost:4.8
    restart: always
    ports:
      - 2368:2368
    volumes:
      - ./ghost/content:/var/lib/ghost/content
    environment:
      - url=http://localhost:2368
    depends_on:
      - db

  db:
    image: mysql:5.7
    restart: always
    ports:
      - 3906:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=cmi
      - MYSQL_USER=ghost
      - MYSQL_PASSWORD=ghost
    volumes:
      - ./ghost/data:/var/lib/mysql
      - ./data/department.sql:/docker-entrypoint-initdb.d/department.sql
      - ./data/research.sql:/docker-entrypoint-initdb.d/research.sql
