version: "3"
services:
  ghost:
    image: ghost:4.8
    restart: always
    ports:
      - 2368:2368
    volumes:
      - ./ghost/content:/var/lib/ghost/content
    environment:
      - url=http://localhost:2368
    depends_on:
      - db

  db:
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=your_mysql_root_password
      - MYSQL_DATABASE=ghost
      - MYSQL_USER=ghost
      - MYSQL_PASSWORD=your_ghost_mysql_password
    volumes:
      - ./ghost/data:/var/lib/mysql
