version: "3.1"

services:
  ghost:
    image: ghost:4.8
    container_name: ecmi-ghost
    restart: always
    ports:
      - 8005:2368
    depends_on:
      ghost-db:
        condition: service_healthy
    environment:
      database__client: mysql
      database__connection__host: ghost-db
      database__connection__user: root
      database__connection__password: ${MYSQL_ROOT_PASSWORD}
      database__connection__database: ${GHOST_MYSQL_DATABASE}

      url: ${PROD_GHOST_URL}

      mail__transport: SMTP
      mail__options__host: smtp.gmail.com
      mail__options__port: 587
      mail__options__secure: false
      mail__options__auth__user: ${GHOST_EMAIL_USER}
      mail__options__auth__pass: ${GHOST_EMAIL_PASS}
    volumes:
      - ./ghost/content:/var/lib/ghost/content

  ghost-dev:
    image: ghost:4.8
    container_name: ecmi-ghost-dev
    restart: always
    ports:
      - 8050:2368
    depends_on:
      ghost-dev-db:
        condition: service_healthy
    environment:
      database__client: mysql
      database__connection__host: ghost-dev-db
      database__connection__user: root
      database__connection__password: ${GHOST_DEV_MYSQL_ROOT_PASSWORD}
      database__connection__database: ${GHOST_DEV_MYSQL_DATABASE}

      url: ${DEV_GHOST_URL}

      mail__transport: SMTP
      mail__options__host: smtp.gmail.com
      mail__options__port: 587
      mail__options__secure: false
      mail__options__auth__user: ${GHOST_EMAIL_USER}
      mail__options__auth__pass: ${GHOST_EMAIL_PASS}
    volumes:
      - ./ghost/dev/content:/var/lib/ghost/content

  ghost-db:
    image: mysql:5.7
    restart: always
    container_name: ecmi-ghost-db
    ports:
      - 127.0.0.1:3340:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${GHOST_MYSQL_DATABASE}
      MYSQL_USER: ${GHOST_MYSQL_USER}
      MYSQL_PASSWORD: ${GHOST_MYSQL_PASSWORD}
    volumes:
      - ./ghost/data:/var/lib/mysql
      - ./my.cnf:/etc/mysql/my.cnf
    healthcheck:
      test: [
          MYSQL_USER
          "CMD-SHELL",
          'mysqladmin ping -h localhost -u $$MYSQL_USER --password=$$MYSQL_PASSWORD && mysql -u $$ --password=$$MYSQL_PASSWORD -e ''SHOW DATABASES LIKE "$$MYSQL_DATABASE";''',
        ]
      interval: 30s
      timeout: 10s
      retries: 5

  ghost-dev-db:
    image: mysql:5.7
    restart: always
    container_name: ecmi-ghost-dev-db
    ports:
      - 127.0.0.1:3355:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${GHOST_DEV_MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${GHOST_DEV_MYSQL_DATABASE}
      MYSQL_USER: ${GHOST_DEV_MYSQL_USER}
      MYSQL_PASSWORD: ${GHOST_DEV_MYSQL_PASSWORD}
    volumes:
      - ./ghost/dev/data:/var/lib/mysql
      - ./my.cnf:/etc/mysql/my.cnf
    healthcheck:
      test:
        [
          "CMD-SHELL",
          'mysqladmin ping -h localhost -u $$MYSQL_USER --password=$$MYSQL_PASSWORD && mysql -u $$MYSQL_USER --password=$$MYSQL_PASSWORD -e ''SHOW DATABASES LIKE "$$MYSQL_DATABASE";''',
        ]
      interval: 30s
      timeout: 10s
      retries: 5

  cmi-db:
    image: mysql:5.7
    restart: always
    container_name: ecmi-cmidb
    ports:
      - 127.0.0.1:3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./data/mysql/cmi:/var/lib/mysql
      # - ./data/department.sql:/docker-entrypoint-initdb.d/department.sql
      # - ./data/research.sql:/docker-entrypoint-initdb.d/research.sql
      # - ./data/manual.sql:/docker-entrypoint-initdb.d/manual.sql
    healthcheck:
      test:
        [
          "CMD-SHELL",
          'mysqladmin ping -h localhost -u $$MYSQL_USER --password=$$MYSQL_PASSWORD && mysql -u $$MYSQL_USER --password=$$MYSQL_PASSWORD -e ''SHOW DATABASES LIKE "$$MYSQL_DATABASE";''',
        ]
      interval: 30s
      timeout: 10s
      retries: 5

  cmi-dev-db:
    image: mysql:5.7
    restart: always
    container_name: ecmi-cmi-dev-db
    ports:
      - 127.0.0.1:3350:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./data/mysql/cmidev:/var/lib/mysql
      # - ./data/department.sql:/docker-entrypoint-initdb.d/department.sql
      # - ./data/research.sql:/docker-entrypoint-initdb.d/research.sql
      # - ./data/manual.sql:/docker-entrypoint-initdb.d/manual.sql
    healthcheck:
      test:
        [
          "CMD-SHELL",
          'mysqladmin ping -h localhost -u $$MYSQL_USER --password=$$MYSQL_PASSWORD && mysql -u $$MYSQL_USER --password=$$MYSQL_PASSWORD -e ''SHOW DATABASES LIKE "$$MYSQL_DATABASE";''',
        ]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  ghost:
  ghost-dev:
  ghost-db:
  ghost-dev-db:
  cmi-db:
  cmi-dev-db:
