name: Deploy Next.js App to Dev

on:
  push:
    branches:
      - dev # Deploy when changes are pushed to the dev branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: Dev
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      PORT: ${{ secrets.PORT }}
      NEXT_GHOST_URL: ${{ secrets.NEXT_GHOST_URL }}
      NEXT_GHOST_CONTENT_API_KEY: ${{ secrets.NEXT_GHOST_CONTENT_API_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Run Prisma migrations
        env:
          DATABASE_URL: ${{ env.DATABASE_URL }}
        run: npx prisma migrate deploy

      - name: Build Next.js app
        run: npm run build

      - name: Deploy to Server
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd /var/www/test/ecmi
            git pull origin dev
            npm install --production
            npm run build
            PORT=${{ env.PORT }} pm2 restart test_ecmi
