name: Deploy Next.js App to Prod

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: Prod
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      NEXT_PUBLIC_GHOST_URL: ${{ secrets.PROD_NEXT_PUBLIC_GHOST_URL }}
      NEXT_PUBLIC_GHOST_CONTENT_API_KEY: ${{ secrets.PROD_GHOST_CONTENT_API }}
      NEXT_PUBLIC_GHOST_ADMIN_URL: ${{ secrets.PROD_GHOST_ADMIN_URL }}
      APP_PORT: 3000
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Run Prisma migrations
        env:
          DATABASE_URL: ${{ env.DATABASE_URL }}
        run: npx prisma migrate deploy

      - name: Build Next.js app
        env: 
          NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: ${{ secrets.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY }}
          CLERK_SECRET_KEY: ${{ secrets.CLERK_SECRET_KEY }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: npm run build

      - name: Upload build artifacts to staging server
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          source: ".next,public,package.json,ecosystem.config.js,prisma"
          target: "/var/www/ecmi-prod"

      - name: Run app on prod port
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

            export DATABASE_URL="${{ secrets.DATABASE_URL }}"

            cd /var/www/ecmi-prod
            npm install --omit=dev
            npm install @prisma/client
            npx prisma migrate deploy
            PORT=3000 pm2 reload cmi_production --update-env || pm2 start npm --name cmi_production -- run start

      # - name: Deploy to Server
      #   uses: appleboy/ssh-action@v0.1.6
      #   with:
      #     host: ${{ secrets.SERVER_IP }}
      #     username: ${{ secrets.SERVER_USER }}
      #     key: ${{ secrets.SSH_KEY }}
      #     port: ${{ secrets.SSH_PORT }}
      #     script: |
      #       export NVM_DIR="$HOME/.nvm"
      #       [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" 
      #       cd /var/www/ecmi
      #       git pull origin dev
      #       npm install --omit=dev
      #       npm install @prisma/client
      #       prisma migrate deploy
      #       export PATH=$PATH:/var/www/ecmi/node_modules/.bin 
      #       npm run build
      #       PORT=${{env.APP_PORT}} pm2 start npm --name cmi_production -- run start || pm2 restart cmi_production
      #     debug: true
